data_prep:
  version: "2.0"
  dataset_name: "vehicle_collision_prediction_calibrated"
  target_column: "collisions"
  binary_target_column: "collisions_binary"
  numerical_features: 
    - "count_trip"
    - "miles"
    - "drive_hours"
    - "count_brakes"
    - "count_accelarations"
    - "time_speeding_hours"
    - "time_phoneuse_hours"
    - "highway_miles"
    - "night_drive_hrs"
    - "maximum_speed"
  categorical_features:
    - "month"
  imputation_strategy: "median"
  
feature_prep:
  create_engineered_features: true
  eps_value: 1.0e-8

model_evaluation:
  split_ratio: 0.2
  evaluation_metric: "PR-AUC"
  cv_folds: 5
  stratify: true
  calibrate_probabilities: true
  calibration_method: "sigmoid"
  threshold_optimization: true
  threshold_strategies:
    - "optimal_f1"
    - "high_precision"
    - "high_recall"

model:
  model_type: "RandomForest"
  model_params:
    n_estimators: 100
    class_weight: "balanced"
    random_state: 42
  n_features_select: null
  hyperparameter_tuning: false



